# Generated by Django 2.2.7 on 2019-11-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repoName', models.CharField(max_length=100)),
                ('author', models.TextField()),
                ('additions', models.IntegerField()),
                ('deletions', models.IntegerField()),
                ('total', models.IntegerField()),
                ('commitDate', models.DateField()),
            ],
        ),
    ]
