# Generated by Django 2.2.7 on 2019-11-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
    ]
