# Generated by Django 2.2.7 on 2019-11-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siter', '0002_remove_commit_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='repoName',
        ),
    ]
