# Generated by Django 2.2.7 on 2019-11-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siter', '0003_remove_commit_reponame'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='repoName',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
